baseURL = 'http://localhost/'
theme = 'agora'
languageCode = 'en-us'
title = 'A-GORA'
defaultContentLanguage = 'bg'
defaultContentLanguageInSubdir = true
canonifyURLs = true

[params]
  loginurl = "https://app.agora/auth/login"
  registerurl = "https://app.agora/auth/signup"
  registerurltalent = "https://app.agora/auth/signup?as=talent"
  registerurlcompany = "https://app.agora/auth/signup?as=business"

[languages]
  [languages.bg]
    languageCode = 'bg-BG'
    languageDirection = 'ltr'
    languageName = 'Български'
    title = 'А-ГОРА'
    weight = 1
  [languages.en]
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'A-GORA'
    weight = 2
